# Generated by Django 4.0.5 on 2022-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('bookName', models.CharField(max_length=100)),
                ('bookURL', models.URLField(max_length=1000)),
            ],
        ),
    ]
