# Generated by Django 4.0.5 on 2022-07-15 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikidthConverter', '0002_booklist_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookList',
            new_name='Book',
        ),
    ]
