# Generated by Django 4.0.5 on 2022-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidthConverter', '0003_rename_booklist_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='fileName',
        ),
        migrations.AddField(
            model_name='book',
            name='EPUBfile',
            field=models.CharField(default='sample_epub', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='PDFfile',
            field=models.CharField(default='sample_pdf', max_length=100),
        ),
    ]
